# only relevant for foresight = myopic or perfect
existing_capacities:
  grouping_years_power: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025, 2030]
  grouping_years_heat: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019] # these should not extend 2020
  threshold_capacity: 10
  conventional_carriers:
  - lignite
  - coal
  - oil
  - uranium
  exit_year:
    gas: 2039
    coal: 2029
