logging_level: INFO

results_dir: 'results/'
summary_dir: results
run: '190416-modular-test'

scenario:
  sectors: [E] # ,E+EV,E+BEV,E+BEV+V2G] # [ E+EV, E+BEV, E+BEV+V2G ]
  simpl: ['']
  lv: [1.0,1.25]#[1.0, 1.125, 1.25, 1.5, 2.0, opt]# or opt
  clusters: [128] #[90, 128, 181] #[45, 64, 90, 128, 181, 256] #, 362] # (2**np.r_[5.5:9:.5]).astype(int) minimum is 37
  opts: ['']  #for pypsa-eur
  sector_opts: [Co2L0-3H-T-H-B-I,Co2L0-3H-T-H-B-I-onwind0,Co2L0p1-3H-T-H-B-I]#,Co2L0p05-3H-T-H-B-I,Co2L0p10-3H-T-H-B-I,Co2L0p20-3H-T-H-B-I,Co2L0p30-3H-T-H-B-I,Co2L0p50-3H-T-H-B-I]#[Co2L-3H-T-H,Co2L0p10-3H-T-H,Co2L0-3H-T-H,Co2L0p20-3H-T-H]   #Co2L-3H-T-H,Co2L0p10-3H-T-H,Co2L0p20-3H-T-HCo2L-3H-T-H,Co2L0p10-3H-T-H,Co2L0p30-3H-T-H,Co2L0p50-3H-T-H] #Co2L-3H,Co2L-3H-T,, LC-FL, LC-T, Ep-T, Co2L-T]
  # Co2L will give default (5%); Co2L0p25 will give 25% CO2 emissions; Co2Lm0p05 will give 5% negative emissions


snapshots:
  # arguments to pd.date_range
  start: "2013-01-01"
  end: "2014-01-01"
  closed: 'left' # end is not inclusive


electricity:
  voltages: [220., 300., 380.]

  extendable_carriers:
    Generator: [] # [OCGT]
    StorageUnit: [] # [battery, H2, CAES]

  max_hours:
    battery: 6
    H2: 168

  conventional_carriers: [] # nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]

atlite:
  nprocesses: 4
  cutout_dir: '../pypsa-eur/cutouts'
  cutouts:
    europe-2013-era5:
      module: era5
      xs: [-12., 35.]
      ys: [72., 33.]
      years: [2013, 2013]
    europe-2013-sarah:
      module: sarah
      resolution: 0.2
      xs: [-12., 42.]
      ys: [65., 33.]
      years: [2013, 2013]

renewable:
  onwind:
    cutout: europe-2013-era5
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    # ScholzPhd Tab 4.3.1: 10MW/km^2
    capacity_per_sqm: 3
    # correction_factor: 0.93
    corine:
      #The selection of CORINE Land Cover [1] types that are allowed for wind and solar are based on [2] p.42 / p.28
      #
      #[1] https://www.eea.europa.eu/ds_resolveuid/C9RK15EA06
      #
      #[2] Scholz, Y. (2012). Renewable energy based electricity supply at low costs: development of the REMix model and application for Europe.
      grid_codes: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
                   24, 25, 26, 27, 28, 29, 31, 32]
      distance: 1000
      distance_grid_codes: [1, 2, 3, 4, 5, 6]
      natura: true
  offwind:
    cutout: europe-2013-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
    # ScholzPhd Tab 4.3.1: 10MW/km^2
    capacity_per_sqm: 3
    height_cutoff: 50
    # correction_factor: 0.93
    corine:
      grid_codes: [44, 255]
      natura: true
  solar:
    cutout: europe-2013-sarah
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180.
    # ScholzPhd Tab 4.3.1: 170 MW/km^2
    capacity_per_sqm: 1.7
    correction_factor: 0.877
    corine:
      grid_codes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
      18, 19, 20, 26, 31, 32]
      natura: true
  hydro:
    cutout: europe-2013-era5
    carriers: [ror, PHS, hydro]
    PHS_max_hours: 6


biomass:
  year: 2030
  scenario: "Med"


sector:
  'central' : True
  'central_fraction' : 0.6
  'dsm_restriction_value' : 0.75  #Set to 0 for no restriction on BEV DSM
  'dsm_restriction_time' : 7  #Time at which SOC of BEV has to be dsm_restriction_value
  'transport_heating_deadband_upper' : 20.
  'transport_heating_deadband_lower' : 15.
  'ICE_lower_degree_factor' : 0.375    #in per cent increase in fuel consumption per degree above deadband
  'ICE_upper_degree_factor' : 1.6
  'EV_lower_degree_factor' : 0.98
  'EV_upper_degree_factor' : 0.63
  'district_heating_loss' : 0.1
  'bev' : True #turns on EV battery
  'bev_availability' : 0.5  #How many cars do smart charging
  'v2g' : True #allows feed-in to grid from EV battery
  'transport_fuel_cell_share' : 0.   #0 means all EVs, 1 means all FCs
  'time_dep_hp_cop' : True
  'retrofitting' : False
  'retroI-fraction' : 0.25
  'retroI-fraction' : 0.55
  'retrofitting-cost_factor' : 1.0
  'tes' : True
  'tes_tau' : 3.
  'boilers' : True
  'chp' : True
  'chp_parameters':
    'eta_elec' : 0.468 #electrical efficiency with no heat output
    'c_v' : 0.15 #loss of fuel for each addition of heat
    'c_m' : 0.75 #backpressure ratio
    'p_nom_ratio' : 1. #ratio of max heat output to max electrical output
  'solar_thermal' : True
  'solar_cf_correction': 0.788457  # =  >>> 1/1.2683
  'marginal_cost_storage' : 0. #1e-4
  'methanation' : True
  'helmeth' : True
  'dac' : True
  'ccs_fraction' : 0.9



costs:
  year: 2030

  # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  discountrate: 0.07
  # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html # noqa: E501
  USD2013_to_EUR2013: 0.7532

  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   Wind: Bla
  marginal_cost: #
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 0.
    battery: 0.

  emission_prices: # only used with the option Ep (emission prices)
    co2: 0.



solving:
  options:
    formulation: kirchhoff
    clip_p_max_pu: 1.e-2
    load_shedding: false
    noisy_costs: true

    min_iterations: 1
    max_iterations: 1
    # max_iterations: 1
    # nhours: 1

  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
  # solver:
  #   name: cplex
  #   threads: 4
  #   lpmethod: 4 # barrier
  #   solutiontype: 2 # non basic solution, ie no crossover
  #   barrier.convergetol: 1.e-5
  #   feasopt.tolerance: 1.e-6

plotting:
  map:
    figsize: [7, 7]
    boundaries: [-10.2, 29, 35,  72]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3 # 1.e+3  #3.e+3

  costs_max: 1200
  costs_threshold: 1


  energy_max: 15000.
  energy_min: -15000.
  energy_threshold: 50.


  vre_techs: ["onwind", "offwind", "solar", "ror"]
  conv_techs: ["OCGT", "CCGT", "Nuclear", "Coal"]
  storage_techs: ["hydro+PHS", "battery", "H2"]
  # store_techs: ["Li ion", "water tanks"]
  load_carriers: ["AC load"] #, "heat load", "Li ion load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"]
  heat_links: ["heat pump", "resistive heater", "CHP heat", "CHP electric",
               "gas boiler", "central heat pump", "central resistive heater", "central CHP heat",
               "central CHP electric", "central gas boiler"]
  heat_generators: ["gas boiler", "central gas boiler", "solar thermal collector", "central solar thermal collector"]
  tech_colors:
    "onwind" : "b"
    "onshore wind" : "b"
    'offwind' : "c"
    'offshore wind' : "c"
    "hydro" : "#3B5323"
    "hydro reservoir" : "#3B5323"
    "ror" : "#78AB46"
    "run of river" : "#78AB46"
    'hydroelectricity' : '#006400'
    'solar' : "y"
    'solar PV' : "y"
    'solar thermal' : 'coral'
    "OCGT" : "wheat"
    "OCGT marginal" : "sandybrown"
    "OCGT-heat" : "orange"
    "gas boiler" : "orange"
    "gas boilers" : "orange"
    "gas boiler marginal" : "orange"
    "gas-to-power/heat" : "orange"
    "gas" : "brown"
    "natural gas" : "brown"
    "lines" : "k"
    "transmission lines" : "k"
    "H2" : "m"
    "hydrogen storage" : "m"
    "battery" : "slategray"
    "battery storage" : "slategray"
    "Nuclear" : "r"
    "Nuclear marginal" : "r"
    "Coal" : "k"
    "Coal marginal" : "k"
    "Lignite" : "grey"
    "Lignite marginal" : "grey"
    "CCGT" : "orange"
    "CCGT marginal" : "orange"
    "heat pumps" : "#76EE00"
    "heat pump" : "#76EE00"
    "air heat pump" : "#76EE00"
    "ground heat pump" : "#40AA00"
    "power-to-heat" : "#40AA00"
    "resistive heater" : "pink"
    "Sabatier" : "#FF1493"
    "methanation" : "#FF1493"
    "power-to-gas" : "#FF1493"
    "power-to-liquid" : "#FFAAE9"
    "helmeth" : "#7D0552"
    "helmeth" : "#7D0552"
    "DAC" : "#E74C3C"
    "co2 stored" : "#123456"
    "CO2 sequestration" : "#123456"
    "co2" : "#123456"
    "Fischer-Tropsch" : "#44DD33"
    "nuclear" : "#303030"
    "water tanks" : "#BBBBBB"
    "hot water storage" : "#BBBBBB"
    "hot water charging" : "#BBBBBB"
    "hot water discharging" : "#999999"
    "CHP" : "r"
    "CHP heat" : "r"
    "CHP electric" : "r"
    "PHS" : "g"
    "Ambient" : "k"
    "Electric load" : "b"
    "Heat load" : "r"
    "Transport load" : "grey"
    "heat" : "darkred"
    "heat demand" : "darkred"
    "electric demand" : "k"
    "Li ion" : "grey"
    "district heating" : "#CC4E5C"
    "retrofitting" : "purple"
    "building retrofitting" : "purple"
    "BEV charger" : "grey"
    "V2G" : "grey"
    "transport" : "grey"
    "electricity" : "k"
    "transport fuel cell" : "#AAAAAA"
    "biogas" : "#800000"
    "solid biomass" : "#DAA520"
  nice_names:
    # OCGT: "Gas"
    # OCGT marginal: "Gas (marginal)"
    offwind: "offshore wind"
    onwind: "onshore wind"
    battery: "Battery storage"
    lines: "Transmission lines"
    AC line: "AC lines"
    AC-AC: "DC lines"
    ror: "Run of river"
  nice_names_n:
    offwind: "offshore\nwind"
    onwind: "onshore\nwind"
    # OCGT: "Gas"
    H2: "Hydrogen\nstorage"
    # OCGT marginal: "Gas (marginal)"
    lines: "transmission\nlines"
    ror: "run of river"
