# SPDX-FileCopyrightText: 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

scenario:
  simpl:
  - ''
  ll:
  - v1.5
  clusters:
  - 6
  opts:
  - '24H'
  sector_opts:
  - ''
  planning_horizons:
  - 2050

countries:
- UA

enable:
  retrieve: true
  retrieve_databundle: true
  retrieve_sector_databundle: false
  retrieve_cost_data: true
  retrieve_cutout: false
