# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "validation" # use this to keep track of runs with different settings

scenario:
  ll:  # allowed transmission line volume expansion, can be any float >= 1.0 with a prefix v|c (today) or "copt"
  - v1.0
  clusters:  # number of nodes in Europe, any integer between 37 (1 node per country-zone) and several hundred
  - 37c
  opts: # only relevant for PyPSA-Eur
  - 'Ept'
  sector_opts: # this is where the main scenario settings are
  - Co2L0-1H-T-H-B-I-A-solar+p3-dist1

snapshots:
  start: "2019-01-01"
  end: "2020-01-01"
  inclusive: 'left' # include start, not end

enable:
  retrieve_cutout: false

electricity:
  co2limit: 1e9

  extendable_carriers:
    Generator: []
    StorageUnit: [] # battery, H2
    Store: []
    Link: [] # H2 pipeline

  # use pandas query strings here, e.g. Country not in ['Germany']
  powerplants_filter: not (DateOut < 2019)

  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]

  estimate_renewable_capacities:
    year: 2019


atlite:
  default_cutout: europe-2019-era5
  cutouts:
    # use 'base' to determine geographical bounds and time span from config
    # base:
      # module: era5
    europe-2019-era5:
      module: era5 # in priority order
      x: [-12., 35.]
      y: [33., 72]
      dx: 0.3
      dy: 0.3
      time: ['2019', '2019']


renewable:
  onwind:
    cutout: europe-2019-era5
  offwind-ac:
    cutout: europe-2019-era5
  offwind-dc:
    cutout: europe-2019-era5
  solar:
    cutout: europe-2019-era5
  hydro:
    cutout: europe-2019-era5

conventional:
  unit_commitment: true
  dynamic_fuel_price: true
  nuclear:
    p_max_pu: "data/nuclear_p_max_pu.csv" # float of file name
  biomass:
    p_max_pu: 0.7


load:
  power_statistics: false # only for files from <2019; set false in order to get ENTSOE transparency data

links:
  include_tyndp: false

costs:
  year: 2020
  emission_prices: # in currency per tonne emission, only used with the option Ep
    co2: 25

solving:
  #tmpdir: "path/to/tmp"
  options:
    load_shedding: true
    rolling_horizon: true
    horizon: 365
