# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "validation" # use this to keep track of runs with different settings

scenario:
  ll:  # allowed transmission line volume expansion, can be any float >= 1.0 with a prefix v|c (today) or "copt"
  - v1.0
  clusters:  # number of nodes in Europe, any integer between 37 (1 node per country-zone) and several hundred
  - 37
  opts: # only relevant for PyPSA-Eur
  - 'Ept'

snapshots:
  start: "2019-01-01"
  end: "2020-01-01"
  inclusive: 'left' # include start, not end

enable:
  retrieve_cutout: false

electricity:
  co2limit: 1e9

  extendable_carriers:
    Generator: []
    StorageUnit: [] # battery, H2
    Store: []
    Link: [] # H2 pipeline

  # use pandas query strings here, e.g. Country not in ['Germany']
  powerplants_filter: not (DateOut < 2019)

  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]

  estimate_renewable_capacities:
    year: 2019


atlite:
  default_cutout: europe-2019-era5
  cutouts:
    # use 'base' to determine geographical bounds and time span from config
    # base:
      # module: era5
    europe-2019-era5:
      module: era5 # in priority order
      x: [-12., 35.]
      y: [33., 72]
      dx: 0.3
      dy: 0.3
      time: ['2019', '2019']


renewable:
  onwind:
    cutout: europe-2019-era5
  offwind-ac:
    cutout: europe-2019-era5
  offwind-dc:
    cutout: europe-2019-era5
  solar:
    cutout: europe-2019-era5
  hydro:
    cutout: europe-2019-era5
    flatten_dispatch: 0.01

conventional:
  unit_commitment: false
  dynamic_fuel_price: true
  nuclear:
    p_max_pu: "data/nuclear_p_max_pu.csv" # float of file name
  biomass:
    p_max_pu: 0.65


load:
  power_statistics: false # only for files from <2019; set false in order to get ENTSOE transparency data


lines:
  s_max_pu: 0.25
  under_construction: 'remove' # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity


links:
  include_tyndp: false

costs:
  year: 2020
  emission_prices: # in currency per tonne emission, only used with the option Ep
    co2: 25

clustering:
  simplify_network:
    exclude_carriers: [oil, coal, lignite, OCGT, CCGT]
  cluster_network:
    consider_efficiency_classes: true


solving:
  #tmpdir: "path/to/tmp"
  options:
    load_shedding: true
    rolling_horizon: false
    horizon: 1000
    overlap: 48
