# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

name: pypsa-eur
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.8
  - pip

  - atlite>=0.2.5
  - dask

  # Dependencies of the workflow itself
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - lxml
  - powerplantmatching>=0.4.8
  - numpy
  - pandas<1.3
  - geopandas
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - progressbar2
  - pyomo
  - matplotlib
  - proj

  # Keep in conda environment when calling ipython
  - ipython

  # GIS dependencies:
  - cartopy
  - descartes
  - rasterio

  # PyPSA-Eur-Sec Dependencies
  - geopy
  - tqdm
  - pytz
  - country_converter
  - tabula-py

  - pip:
    - git+https://github.com/pypsa/pypsa.git#egg=pypsa
    - vresutils>=0.3.1
    - tsam>=1.1.0
