# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-eur
channels:
  - bioconda
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - affine=2.3.0
  - appdirs=1.4.3
  - atlite=0.0.3
  - attrs=19.3.0
  - backcall=0.1.0
  - beautifulsoup4=4.9.1
  - blas=1.0
  - blosc=1.16.3
  - bokeh=2.0.2
  - bottleneck=1.3.2
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - cartopy=0.17.0
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cfitsio=3.470
  - cftime=1.1.2
  - chardet=3.0.4
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.4.1
  - coincbc=2.10.5
  - configargparse=1.1
  - cryptography=2.9.2
  - curl=7.67.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask=2.17.2
  - dask-core=2.17.2
  - datrie=0.8.2
  - dbus=1.13.14
  - decorator=4.4.2
  - distributed=2.17.0
  - docutils=0.16
  - entsoe-py=0.2.10
  - expat=2.2.6
  - fiona=1.8.11
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - fsspec=0.7.4
  - gdal=3.0.2
  - geographiclib=1.50
  - geopandas=0.6.1
  - geopy=1.22.0
  - geos=3.8.0
  - geotiff=1.5.1
  - giflib=5.1.4
  - gitdb=4.0.2
  - gitpython=3.1.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gurobi=9.0.2
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.1
  - icu=58.2
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2020.1
  - ipopt=3.13.2
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.15.1
  - jpeg=9b
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter_core=4.6.3
  - kealib=1.4.7
  - kiwisolver=1.2.0
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libboost=1.67.0
  - libcblas=3.8.0
  - libcurl=7.67.0
  - libdap4=3.19.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgdal=3.0.2
  - libgfortran-ng=7.3.0
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.5
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - libxslt=1.1.33
  - locket=0.2.0
  - lxml=4.5.0
  - lz4-c=1.8.1.2
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - memory_profiler=0.55.0
  - metis=5.1.0
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - mock=4.0.2
  - more-itertools=8.3.0
  - msgpack-python=1.0.0
  - munch=2.5.0
  - nbformat=5.0.6
  - ncurses=6.2
  - netcdf4=1.4.2
  - networkx=2.4
  - nose=1.3.7
  - numexpr=2.7.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1g
  - owslib=0.19.2
  - packaging=20.3
  - pandas=1.0.3
  - parso=0.7.0
  - partd=1.1.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.1.2
  - pip=20.0.2
  - pixman=0.38.0
  - pluggy=0.13.1
  - ply=3.11
  - poppler=0.65.0
  - poppler-data=0.4.9
  - postgresql=11.5
  - powerplantmatching=0.4.5
  - progressbar2=3.37.1
  - proj=6.2.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - py=1.8.1
  - pycountry=19.8.18
  - pycparser=2.20
  - pyepsg=0.4.0
  - pygments=2.6.1
  - pykdtree=1.3.1
  - pyomo=5.6.9
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pypsa=0.17.0
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pyshp=2.1.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=5.4.2
  - pytest-runner=5.2
  - python=3.7.7
  - python-dateutil=2.8.1
  - python-utils=2.3.0
  - python_abi=3.7
  - pytz=2020.1
  - pyutilib=5.8.0
  - pyyaml=5.3.1
  - qt=5.9.7
  - rasterio=1.1.0
  - ratelimiter=1.2.0
  - readline=8.0
  - requests=2.23.0
  - rtree=0.9.4
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.1
  - setuptools=47.1.1
  - shapely=1.7.0
  - sip=4.19.8
  - six=1.15.0
  - smmap=3.0.2
  - snakemake-minimal=5.19.2
  - snappy=1.1.7
  - snuggs=1.4.7
  - sortedcontainers=2.1.0
  - soupsieve=2.0.1
  - sqlite=3.31.1
  - tbb=2018.0.5
  - tblib=1.6.0
  - tiledb=1.6.3
  - tk=8.6.8
  - toolz=0.10.0
  - toposort=1.5
  - tornado=6.0.4
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - tzcode=2020a
  - urllib3=1.25.8
  - wcwidth=0.1.9
  - wheel=0.34.2
  - wrapt=1.12.1
  - xarray=0.15.1
  - xerces-c=3.2.2
  - xlrd=1.2.0
  - xz=5.2.5
  - yaml=0.1.7
  - zict=2.0.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cdsapi==0.2.7
    - countrycode==0.2
    - descartes==1.1.0
    - geokit==1.1.2
    - glaes==1.1.2
    - tqdm==4.46.1
    - vresutils==0.3.1
