# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-eur
channels:
  - conda-forge
  - bioconda
  - http://conda.anaconda.org/gurobi
dependencies:
  - python>=3.8
  - pip
  - mamba # esp for windows build

  - pypsa>=0.17.1 
  - atlite>=0.2.2
  - dask<=2021.3.1 # until https://github.com/dask/dask/issues/7583 is solved

  # Dependencies of the workflow itself
  - xlrd
  - openpyxl
  - scikit-learn
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - lxml
  - powerplantmatching>=0.4.8
  - numpy<=1.19.0 # otherwise macos fails


  # Keep in conda environment when calling ipython
  - ipython

  # GIS dependencies:
  - cartopy
  - descartes

  - pip:
    - vresutils==0.3.1
    - tsam>=1.1.0
