# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: pypsa-eur-docs
channels:
  - conda-forge
dependencies:
  - python<=3.7
  - pip
  - pypsa>=0.17.1
  - atlite=0.0.3
  - pre-commit

  # Dependencies of the workflow itself
  - scikit-learn
  - pycountry
  - seaborn
  - memory_profiler
  - yaml
  - pytables
  - powerplantmatching>=0.4.3

  # Second order dependencies which should really be deps of atlite
  - xarray
  - progressbar2
  - pyyaml>=5.1.0

  # GIS dependencies have to come all from conda-forge
  - cartopy
  - fiona
  - proj
  - pyshp
  - geopandas
  - rasterio
  - shapely
  - libgdal

  - pip:
    - vresutils==0.3.1
    - git+https://github.com/PyPSA/glaes.git#egg=glaes
    - git+https://github.com/PyPSA/geokit.git#egg=geokit
    - cdsapi
    - sphinx
    - sphinx_rtd_theme
