# SPDX-FileCopyrightText: : 2017-2022 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

name: pypsa-eur
channels:
  - bioconda
  - http://conda.anaconda.org/gurobi
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - affine=2.3.1
  - alsa-lib=1.2.3.2
  - altair=4.2.0
  - ampl-mp=3.1.0
  - amply=0.1.5
  - anyio=3.6.1
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=8.0.0
  - asttokens=2.0.5
  - atlite=0.2.9
  - attrs=21.4.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - babel=2.10.3
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - blinker=1.4
  - blosc=1.21.1
  - bokeh=2.4.3
  - boost-cpp=1.74.0
  - bottleneck=1.3.5
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15.1
  - cachetools=5.0.0
  - cairo=1.16.0
  - cartopy=0.20.1
  - cdsapi=0.5.1
  - certifi=2022.6.15.1
  - cffi=1.15.1
  - cfitsio=4.0.0
  - cftime=1.6.1
  - charset-normalizer=2.1.0
  - click=8.0.4
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.1.0
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.7
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.8
  - colorama=0.4.5
  - colorcet=3.0.0
  - commonmark=0.9.1
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - country_converter=0.7.4
  - cryptography=37.0.4
  - curl=7.83.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2022.7.0
  - dask-core=2022.7.0
  - dataclasses=0.8
  - datrie=0.8.2
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecation=2.1.0
  - descartes=1.1.0
  - distributed=2022.7.0
  - distro=1.6.0
  - docutils=0.19
  - dpath=2.0.6
  - entrypoints=0.4
  - entsoe-py=0.5.4
  - et_xmlfile=1.0.1
  - executing=0.8.3
  - expat=2.4.8
  - filelock=3.7.1
  - fiona=1.8.20
  - flit-core=3.7.1
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.34.4
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=2022.5.0
  - future=0.18.2
  - gdal=3.3.3
  - geographiclib=1.52
  - geojson-rewind=1.0.2
  - geopandas=0.11.0
  - geopandas-base=0.11.0
  - geopy=2.2.0
  - geos=3.10.0
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glog=0.6.0
  - gmp=6.2.1
  - graphite2=1.3.13
  - grpc-cpp=1.45.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - harfbuzz=2.9.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icu=68.2
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.8.0
  - iniconfig=1.1.1
  - ipykernel=6.15.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=4.7.2
  - jupyter_client=7.3.4
  - jupyter_core=4.10.0
  - jupyter_server=1.18.1
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcrc32c=1.1.2
  - libcurl=7.83.1
  - libdap4=3.20.6
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgdal=3.3.3
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libgoogle-cloud=1.40.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.5
  - libprotobuf=3.20.1
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libutf8proc=2.7.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzip=1.9.2
  - libzlib=1.2.12
  - locket=1.0.0
  - lxml=4.8.0
  - lz4=4.0.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mapclassify=2.4.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - memory_profiler=0.60.0
  - metis=5.1.0
  - mistune=0.8.4
  - msgpack-python=1.0.4
  - mumps-include=5.2.1
  - mumps-seq=5.2.1
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclassic=0.4.3
  - nbclient=0.6.6
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf4=1.6.0
  - networkx=2.8.4
  - nomkl=1.0
  - notebook=6.4.12
  - notebook-shim=0.1.0
  - nspr=4.32
  - nss=3.78
  - numexpr=2.8.3
  - numpy=1.23.1
  - openjdk=11.0.9.1
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1q
  - orc=1.7.5
  - packaging=21.3
  - pandas=1.4.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.2.0
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - pixman=0.40.0
  - plac=1.3.5
  - pluggy=1.0.0
  - ply=3.11
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.5
  - powerplantmatching=0.5.4
  - progressbar2=4.0.0
  - proj=8.1.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - protobuf=3.20.1
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.6.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pyarrow=8.0.0
  - pycountry=20.7.3
  - pycparser=2.21
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pydeck=0.7.1
  - pygments=2.12.0
  - pympler=0.9
  - pyomo=6.4.1
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.2.1
  - pypsa=0.20.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pyshp=2.3.0
  - pysocks=1.7.1
  - pytables=3.7.0
  - pytest=7.1.2
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python-tzdata=2022.1
  - python-utils=3.3.3
  - python_abi=3.9
  - pytz=2022.1
  - pytz-deprecation-shim=0.1.0.post0
  - pyviz_comms=2.2.0
  - pyxlsb=1.0.9
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt=5.12.9
  - rasterio=1.2.9
  - ratelimiter=1.2.0
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - retry=0.9.2
  - rich=12.5.1
  - rtree=1.0.0
  - s2n=1.0.10
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - scotch=6.0.9
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - semver=2.13.0
  - send2trash=1.8.0
  - setuptools=63.2.0
  - setuptools-scm=7.0.5
  - setuptools_scm=7.0.5
  - shapely=1.8.0
  - six=1.16.0
  - smart_open=6.0.0
  - smmap=3.0.5
  - snakemake-minimal=7.8.5
  - snappy=1.1.9
  - sniffio=1.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sqlite=3.39.1
  - stack_data=0.3.0
  - statsmodels=0.13.2
  - stopit=1.1.2
  - streamlit=1.10.0
  - tabula-py=2.2.0
  - tabulate=0.8.10
  - tblib=1.7.0
  - tenacity=8.0.1
  - terminado=0.15.0
  - threadpoolctl=3.1.0
  - tiledb=2.3.4
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - toposort=1.7
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.3.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzcode=2022a
  - tzdata=2022a
  - tzlocal=4.2
  - unicodedata2=14.0.0
  - unidecode=1.3.4
  - unixodbc=2.3.10
  - urllib3=1.26.10
  - validators=0.18.2
  - watchdog=2.1.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.3
  - wheel=0.37.1
  - widgetsnbextension=3.6.1
  - wrapt=1.14.1
  - xarray=2022.3.0
  - xerces-c=3.2.3
  - xlrd=2.0.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.6.0
  - xz=5.2.5
  - yaml=0.2.5
  - yte=1.5.1
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - countrycode==0.2
    - tsam==2.1.0
    - vresutils==0.3.1