# SPDX-FileCopyrightText: : 2017-2022 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

name: pypsa-eur
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.9
  - pip

  - pypsa>=0.20
  - atlite>=0.2.9
  - dask

  # Dependencies of the workflow itself
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - lxml
  - powerplantmatching>=0.5.4
  - numpy
  - pandas
  - geopandas>=0.11.0
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely<2.0 # need to address deprecations
  - progressbar2
  - pyomo
  - matplotlib
  - proj
  - fiona # <= 1.18.20  # Till issue https://github.com/Toblerity/Fiona/issues/1085 is not solved
  - country_converter

  # Keep in conda environment when calling ipython
  - ipython

  # GIS dependencies:
  - cartopy>=0.16
  - descartes
  - rasterio<=1.2.9  # 1.2.10 creates error https://github.com/PyPSA/atlite/issues/238

  # PyPSA-Eur-Sec Dependencies
  - geopy
  - tqdm
  - pytz
  - tabula-py
  - pyxlsb

  - pip:
    - vresutils>=0.3.1
    - tsam>=1.1.0
